/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    AEmpty: typeof import('ant-design-vue/es')['Empty']
    AModal: typeof import('ant-design-vue/es')['Modal']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    ATransfer: typeof import('ant-design-vue/es')['Transfer']
    ATree: typeof import('ant-design-vue/es')['Tree']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SEchart: typeof import('./src/components/SEchart.vue')['default']
    SLoading: typeof import('./src/components/SLoading.vue')['default']
    StepProgress: typeof import('./src/components/StepProgress.vue')['default']
    TransferTree: typeof import('./src/components/TransferTree.vue')['default']
  }
}
